- hosts: all
  become: true

  vars:
    http_basic_password: "{{ lookup('password', '~/.ansible/'+ansible_hostname+'/app/'+app.name+'_'+app.environment+'_http_basic_password length={{password_length}}') }}"

  tasks:
  - name: "password protect site with username: admin password: {{http_basic_password}}"
    htpasswd:
      path: /etc/nginx/auth/{{app.environment}}/{{app.name}}.htpasswd
      name: admin
      password: "{{http_basic_password}}"
      owner: root
      group: "{{nginx.user}}"
      mode: 0640
    when: password_protect

# auth_basic           "Restricted Area";
# auth_basic_user_file /etc/nginx/auth/{{app.environment}}/{{app.name}}.htpasswd;
