- hosts: all
  become: true

  tasks:
  - name: make /etc/nginx/ssl directory
    file:
      path: /etc/nginx/ssl
      state: directory

  - name: check DHE param exists
    stat:
      path: /etc/nginx/ssl/dhparam.pem
    register: dhparam

  - name: generate DHE param
    shell: "openssl dhparam -out /etc/nginx/ssl/dhparam.pem 2048"
    when: not dhparam.stat.exists
