- hosts: all
  become: true

  tasks:
    - name: add certbot repository
      apt_repository:
        repo: 'ppa:certbot/certbot'
        state: present
      when: ansible_distribution_major_version|int <= 18

    - name: install certbot
      apt:
        name: certbot
        state: latest
