- hosts: all
  become: true

  tasks:
  - name: get pubkey
    shell: curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -

  - name: add to sources
    shell: echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

  - name: install yarn
    apt:
      name: yarn
      state: latest
      update_cache: true
