- hosts: all
  become: true

  tasks:
    - name: install libsasl2-modules
      apt:
        pkg: libsasl2-modules
        state: present

    - name: append to postfix main.cf
      blockinfile:
        path: /etc/postfix/main.cf
        block: |
          smtp_sasl_auth_enable = yes
          smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd
          smtp_sasl_security_options = noanonymous
          smtp_sasl_tls_security_options = noanonymous
          smtp_tls_security_level = encrypt
          header_size_limit = 4096000
          relayhost = [smtp.sendgrid.net]:2525
      when: gcp_postfix_required

    - name: create sasl_password file
      template:
        src: "{{inventory_dir}}/files/gcp/sasl_passwd"
        dest: /etc/postfix/sasl_passwd
      when: gcp_postfix_required

    - name: set permissions on sasl_passwd file
      command: chmod 0600 /etc/postfix/sasl_passwd
      when: gcp_postfix_required

    - name: postmap /etc/postfix/sasl_password file
      command: postmap /etc/postfix/sasl_passwd
      when: gcp_postfix_required

    - name: remove plaintext file
      file:
        state: absent
        path: /etc/postfix/sasl_passwd

    - name: restart postfix
      service: name=postfix state=restarted
      when: gcp_postfix_required

